---
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch.
  package:
    name: elasticsearch{{ "-" ~ __elasticsearch_version | default("") }}
    state: present
